# Generated by Django 3.2.7 on 2021-12-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211224_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'github'), ('kakao', 'kakao')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
