# Generated by Django 3.2.7 on 2021-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.IntegerField(help_text='얼마나 많은 사람들이 지낼껀지'),
        ),
    ]
